#define ICON_RPG_MIN 0xe900
#define ICON_RPG_MAX 0xeaee

#define ICON_RPG_AXE "\xee\xa4\x97"            // U+E917
#define ICON_RPG_BOOK "\xee\xa4\xba"           // U+E93A
#define ICON_RPG_ARROW "\xee\xa5\x85"          // U+E945
#define ICON_RPG_ATTACK "\xee\xa5\x86"         // U+E946
#define ICON_RPG_BROKEN_BONE "\xee\xa5\x87"    // U+E947
#define ICON_RPG_BROKEN_HEART "\xee\xa5\x89"   // U+E949
#define ICON_RPG_BROKEN_SHIELD "\xee\xa5\x8a"  // U+E94A
#define ICON_RPG_BROKEN_SKULL "\xee\xa5\x8b"   // U+E94B
#define ICON_RPG_FIRE_ZONE "\xee\xa5\x8f"      // U+E94F
#define ICON_RPG_CAMPFIRE "\xee\xa5\x94"       // U+E954
#define ICON_RPG_CIRCLE_X "\xee\xa5\x95"       // U+E955
#define ICON_RPG_CARROT "\xee\xa5\x9c"         // U+E95C
#define ICON_RPG_CHEESE "\xee\xa5\xa1"         // U+E961
#define ICON_RPG_TURKEY "\xee\xa5\xa4"         // U+E964
#define ICON_RPG_VIAL "\xee\xa5\xb3"           // U+E973
#define ICON_RPG_BROKEN_HELMET "\xee\xa5\xb5"  // U+E975
#define ICON_RPG_BROKEN_SHIELD "\xee\xa5\xb6"  // U+E976
#define ICON_RPG_BLOODY_SWORD "\xee\xa5\xb7"   // U+E977
#define ICON_RPG_CROSSBOW "\xee\xa5\xb8"       // U+E978
#define ICON_RPG_MAGIC_STAFF "\xee\xa6\x84"    // U+E984
#define ICON_RPG_CRYSTALS "\xee\xa6\x85"       // U+E985
#define ICON_RPG_RECYCLE "\xee\xa6\x88"        // U+E988
#define ICON_RPG_MAGIC "\xee\xa7\x82"          // U+E9C2
#define ICON_RPG_WARHAMMER "\xee\xa7\x8c"      // U+E9CC

#define ICON_RPG_UNKNOWN12 "\xee\xa7\x83"     // U+E9C3
#define ICON_RPG_UNKNOWN13 "\xee\xa7\x84"     // U+E9C4
#define ICON_RPG_FISH "\xee\xa7\x85"          // U+E9C5
#define ICON_RPG_UNKNOWN14 "\xee\xa7\x86"     // U+E9C6
#define ICON_RPG_FLAME_ALT "\xee\xa7\x87"     // U+E9C7
#define ICON_RPG_JEWEL "\xee\xa7\x9f"         // U+E9DF
#define ICON_RPG_INGOT "\xee\xa7\xa4"         // U+E9E4
#define ICON_RPG_GRASS "\xee\xa7\xa7"         // U+E9E7
#define ICON_RPG_HAND "\xee\xa7\xb1"          // U+E9F1
#define ICON_RPG_QUESTION "\xee\xa7\xbf"      // U+E9FF
#define ICON_RPG_WEIGHT "\xee\xa8\x94"        // U+EA14
#define ICON_RPG_FOOD "\xee\xa8\x98"          // U+EA18
#define ICON_RPG_DAGGER "\xee\xa8\x99"        // U+EA19
#define ICON_RPG_WARHAMMER "\xee\xa8\x9d"     // U+EA1D
#define ICON_RPG_SAVE "\xee\xa8\xb4"          // U+EA34
#define ICON_RPG_PAWN "\xee\xa9\x97"          // U+EA57
#define ICON_RPG_PLAYER "\xee\xa9\xaf"        // U+EA6F
#define ICON_RPG_LOAD "\xee\xaa\x8d"          // U+EA8D
#define ICON_RPG_SCROLL "\xee\xaa\x8f"        // U+EA8F
#define ICON_RPG_HEART "\xee\xab\x9a"         // U+EADA
#define ICON_RPG_HEALTH_CROSS "\xee\xa7\xb5"  // U+E9F5
#define ICON_RPG_ARMOR "\xee\xa5\xb6"         // U+E976
#define ICON_RPG_CRITICAL "\xee\xa9\x9e"      // U+EA5E
#define ICON_RPG_WEAPON "\xee\xa6\xa4"        // U+E9A4
#define ICON_RPG_WEAPON_TYPE "\xee\xa5\x87"   // U+E947
#define ICON_RPG_SKILL "\xee\xa6\xaf"         // U+E9AF
#define ICON_RPG_VALUE "\xee\xa7\xa0"         // U+EA40
